name: "Cleanup node_modules and .gitignore"
description: "Removes all node_modules folders and ensures .gitignore excludes them"
author: "TheKitoInc"
runs:
  using: "composite"
  steps:
    - name: Remove all node_modules folders
      shell: bash
      run: |
        echo "Searching for node_modules folders..."
        find . -type d -name node_modules -prune -exec rm -rf '{}' +
        echo "All node_modules removed."

    - name: Ensure node_modules is in .gitignore
      shell: bash
      run: |
        touch .gitignore
        if ! grep -q "^node_modules/" .gitignore ; then
          echo "node_modules/" >> .gitignore
          echo "Added node_modules/ to .gitignore"
        else
          echo ".gitignore already contains node_modules/"
        fi

    - name: Commit changes
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .gitignore
        git add -u
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "ci: cleanup node_modules and update .gitignore"
          git push
        fi
