name: Auto Release Tag with Latest

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest semver tag
        id: get_tag
        run: |
          latest_tag=$(git tag -l "v*.*.*" --sort=-v:refname | head -n1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            latest_tag="v1.0.0"
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate new tag
        id: new_tag
        run: |
          latest="${{ steps.get_tag.outputs.latest_tag }}"
          IFS='.' read -r major minor patch <<< "${latest#v}"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.new_tag.outputs.new_tag }}
          git push origin ${{ steps.new_tag.outputs.new_tag }}

      - name: Create or update 'latest' tag
        run: |
          git tag -f latest
          git push origin latest --force

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.new_tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
